version: '3.8'
services:
  api:
    container_name: nest_api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      - PORT=5000
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    networks:
      - proyecto_final

  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - proyecto_final

networks:
  proyecto_final:
    driver: bridge
