version: '3.8'
services:
  api:
    container_name: nest_api
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - proyecto_final

  database:
    image: postgres
    container_name: database
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - proyecto_final

networks:
  proyecto_final:
    driver: bridge
